# Generated by Django 4.2.27 on 2025-12-16 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workers", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0002_create_default_panchayat"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("wet", "Wet"),
                            ("dry", "Dry"),
                            ("ewaste", "E-waste"),
                            ("hazardous", "Hazardous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entered_weight", models.FloatField()),
                ("verified_weight", models.FloatField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="waste_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "worker_proof_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pickup_proofs/"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workers.workerprofile",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.ward",
                    ),
                ),
                (
                    "waste_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup",
                        to="waste.wasterecord",
                    ),
                ),
            ],
        ),
    ]
